---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.

```{r}
library(tidyverse)
library(shiny)

ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)

server1 <- function(input, output, server) {
  output$greeting <- renderText(paste0("Hello ", input$name))
}

shinyApp(ui, server1)
```



```{r}
ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)

server2 <- function(input, output, server) {
  greeting <- renderText(paste0("Hello ", input$name))
  output$greeting <- renderText(greeting())
}



shinyApp(ui, server2)
```

```{r}

ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)

server3 <- function(input, output, server) {
    output$greeting <- renderText(paste0("Hello", input$name))

}

shinyApp(ui, server3)
```


2.

server1 <- function(input, output, session) {
  c <- reactive(input$a + input$b)
  e <- reactive(c() + input$d)
  output$f <- renderText(e())

|A> ===> 
      ===> >C> ==>
|B> ===>        ==> >e> ==> >F|
           |D> ==>







server2 <- function(input, output, session) {
  x <- reactive(input$x1 + input$x2 + input$x3)
  y <- reactive(input$y1 + input$y2)
  output$z <- renderText(x() / y())
}

|x1> ==>
|x2> ==> >X>
|x3> ==>
                ==>==>==> >Z|
|y1> ==>
      ==> >Y>
|y2> ==>



server3 <- function(input, output, session) {
  d <- reactive(c() ^ input$d)
  a <- reactive(input$a * 10)
  c <- reactive(b() / input$c) 
  b <- reactive(a() + input$b)
}

|a> ==> >A> ===>
              ===> >B> ===>
         b> ==>          ===> >C> ===> 
                   |c> ==>          ===> >D|
                               |d> ==> 





