---
title: "quiz3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

All work presented is my own, and I have followed all rules for collaboration.”
Caleb Hamblen

Question 1 (5 points). Suppose you do the following:

You go to your GitHub site and make a change to the README file (adding a sentence, for example).
In R Studio, you update one of your .Rmd files, adding a line of code and commit the file.
You attempt to push the new file to your GitHub site.
Once you get to the third step, you’ll get an error when you try to push. Why? What do you need to do first before you make the push in Step 3?

You need to pull the README file into R before pushing the Rmd.

Question 2 (6 points). Give 2 advantages of using Git and GitHub. These must be advantages that we discussed in class (so you should not simply google “advantages of Git” and give the first two things that pop up).

1. It is easy to collaborate with other students( or proffesors) on projects since they can be shared on a unique site.

2. By pushing it to Git it allows the user to create a "save" so that they could go back and access a working version of the code should things go wrong. 

Question 3 (6 points). Choose 1 of the 12 principles of the ethical practice of data science that you think is the most difficult to execute. Give a short, possibly hypothetical, example that illustrates how that principle could be difficult to follow.

Recognize and mitigate bias in ourselves and in the data we use.

I think this one might be the hardest to adhere to since it can be hard to recognize your own biases. If you were working on a solo project and didn't have anyone else to check in with, it could be easy to have inherent biases that are not known to you. 


Question 4 (6 points). The authors of Data Feminism argued that data scientists should “embrace emotion,” not ignore it when building visuals. State the example that the authors used to show how emotion can be used to make a visual stronger. Then, give an argument against “embracing emotion.” In other words, give an argument that data visualizations should be devoid of emotion as much as possible, even if that’s not what you believe.

In Data Feminism they used an animated graphic on US gun deaths that showed the potential years taken away. While emotion can be used to "enhance" a takeaway, one reason to avoid emotion in data is that you don't want to manipulate your data to fulfill your cause. A big part of the data ethics is not to let bias become a part of your process.

Question 5 (2 points). These two points are given for committing your .Rmd and .html files with a commit message correctly, and pushing them to your GitHub site.
